# -*- coding: utf-8 -*-
""": Hugging Face Model Exploration.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U5n3HtkqthErgpts4p_0_eD22aTahVAV
"""

!pip install transformers torch

from transformers import AutoTokenizer, AutoModelForSequenceClassification, pipeline

model_name = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name)

classifier = pipeline("sentiment-analysis", model=model, tokenizer=tokenizer)

sentences = [
    "I love using tools!",
    "This is the worst experience ever.",
    "The workshop was okay, not too good or bad."
]

for text in sentences:
    result = classifier(text)
    print(f"Input: {text}")
    print(f"Output: {result}\n")

summarizer = pipeline("summarization", model="facebook/bart-large-cnn")

text = """Nitika is a computer science student who recently started learning about Artificial Intelligence.
She is particularly interested in how large language models like GPT and BERT work.
Nitika spends a lot of time experimenting with prompt engineering and tries different techniques
such as zero-shot prompting, few-shot prompting, and chain-of-thought reasoning.
Apart from academics, Nitika also enjoys reading books and exploring new technologies in her free time.
"""

summary = summarizer(text, max_length=50, min_length=20, do_sample=False)
print("Original Text:\n", text)
print("\nGenerated Summary:\n", summary[0]['summary_text'])